name: teste

on:
  workflow_dispatch:

jobs:
  run_r_and_commit:
    runs-on: self-hosted

    steps:

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Mount Z
        run: |
          sudo mount -t drvfs Z: /mnt/z
        
      - name: Run R script
        run: |
          Rscript -e "download.file('ftp://ftp.datasus.gov.br/cnes/CEP_BRASIL.ZIP', '/mnt/z/cep.zip', mode = 'wb')"
