name: teste

on:
  workflow_dispatch:

jobs:
  run_r_and_commit:
    runs-on: self-hosted

    steps:
        
      - name: Run R script
        run: |
          Rscript -e "download.file('ftp://ftp.datasus.gov.br/cnes/CEP_BRASIL.ZIP', '/mnt/f/cep.zip', mode = 'wb')"
